### ISSUE TITLE
Keyboard 

### ISSUE THREAD

**Issue by FaRzad-845** [nathvarun/professional-animations-in-react-native#1]
when i use keyboard it covers screen and it goes messy ... 
how can we fix it ?

**Comment by nathvarun** [comment]
I haven't given this a try but looks like it should work. 

A temporary fix I've made for the problem with the keyboard is to change the first container view with this:
`<KeyboardAvoidingView style={{ flex: 1, backgroundColor: 'white', justifyContent: 'flex-end', }} behavior="padding" enabled>`
and also add to the animated container of the inputs this styles:               
```
backgroundColor: '#fff',
borderTopLeftRadius: 30,
borderTopRightRadius: 30,
```
